on:
  push:
    branches-ignore:
      - master

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i
      - run: npm run release-toolkit verify
