on:
  push:
    branches-ignore:
      - master

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npx helloitsjoe/release-toolkit#v1.0.0 verify
